services:
  vue-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /mnt/storage/docker_volume/hobist_frontend:/app/node_modules
    environment:
      - NODE_ENV=development
